name: FRONT-END - Deploy to Production

on:
  workflow_dispatch: {}

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Install Node 16
        timeout-minutes: 1
        uses: actions/setup-node@v2
        with:
          node-version: 16     

      - name: Install modules
        run: yarn install --prefer-offline --non-interactive
        working-directory: app/

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::865964335034:role/github_workflow_platform_role 
          role-skip-session-tagging: true
          role-duration-seconds: 900        

      - name: Build
        run: scripts/cicd/build.sh
        env:
          CLOUDFRONT_S3: "s3://atc-stitcher-frontend-prod/"
          CLOUDFRONT_ID: "E15CBDY7HEGEV5"
          REACT_APP_API_ENDPOINT: "/api/v1/"
          CI: false
        working-directory: app/